### ISSUE TITLE
How do I use an interface in a field of another interface

### ISSUE THREAD

**Issue by taimo42** [graphql-dotnet/graphql-dotnet#1674]
I'm currenty trying to migrate my code from the last released version 2.4.0 to version 3.0.0-preview-1490. But I'm a little bit stuck because of the following issue.

Let's say I have a class hierarchy like this:

```C#
public abstract class Skin { public string Colour { get; }}
public class Fur : Skin { ... }
public class Feather : Skin { ... }
```

And an appropriate structure in my graphql types:

```C#
public class SkinInterface : InterfaceGraphType<Skin>
{
	public SkinInterface()
	{
		Name = "Skin";		
		Field<NonNullGraphType<StringGraphType>>("colour", "The colour of the skin");		
	}
}

public class FurObject: ObjectGraphType<Fur>
{
	public FurObject()
	{
		this.Name = "Fur";		

		Field<NonNullGraphType<StringGraphType>>("colour", "The colour of the skin");		
			resolve: context => context.Source.Colour);				
		// ... some more fur specific fields
		
		this.Interface<SkinInterface>();
	}
}


public class FeatherObject: ObjectGraphType<Feather>
{
	public FeatherObject()
	{
		this.Name = "Feather";
		
		Field<NonNullGraphType<StringGraphType>>("colour", "The colour of the skin");		
			resolve: context => context.Source.Colour);				
		// ... some more Feather specific fields
		
		this.Interface<SkinInterface>();
	}
}
```

So far so good. Everything is working fine. But now I want to use this in another hierarchy. So I have also the following classes:

```C#
public abstract class Animal { 	public int Age { get; } }
public class Cat : Animal { ... }
public class Bird : Animal { ... }
```

And now I use the `SkinInterface` as the type of a field of another interface, like this:

```C#
public class AnimalInterface : InterfaceGraphType<Animal>
{
	public AnimalInterface()
	{
		Name = "Animal";
		
		Field<NonNullGraphType<IntGraphType>>("age", "The age of the animal");		
		Field<NonNullGraphType<SkinInterface>>("skin", "The skin of the animal");		
	}
}
```

But the `skin` field of the objects who implements `AnimalInterface` has the object type which implements `SkinInterface`, like this:

```C#
public class CatObject: ObjectGraphType<Cat>
{
	public CatObject()
	{
		this.Name = "Cat";
		
		Field<NonNullGraphType<IntGraphType>>("age", "The age of the animal", 
			resolve: context => context.Source.Age);				
		Field<NonNullGraphType<FurObject>>("skin", "The skin of the animal");		
			
		// ... some more cat specific fields
		
		this.Interface<AnimalInterface>();
	}
}

public class BirdObject: ObjectGraphType<Bird>
{
	public BirdObject()
	{
		this.Name = "Bird";
		
		Field<NonNullGraphType<IntGraphType>>("age", "The age of the animal", 
			resolve: context => context.Source.Age);				
		Field<NonNullGraphType<FeatherObject>>("skin", "The skin of the animal");		
		// ... some more bird specific fields
		
		this.Interface<AnimalInterface>();
	}
}
```

But now this setup leads to the following error when executing a graphql query:

```
GraphQL.ExecutionError: Type 'Bird' (BirdObject) does not implement 'Animal' interface. Field 'Bird.skin' must be of type 'NonNullGraphType<SkinInterface>', but in fact it is of type 'NonNullGraphType<FeatherObject>'.
```

What I would like to achive is, that when the client is requesting the field `skin` of type `Bird`, it is right away of the type `FeatherObject` without doing a cast by using `... on FeatherObject`. 

This was working in version 2.4.0. 

Was this behaviour changed by intention? 
Do you have another idea how I can achieve the same thing?

Your help would be very appreciated.

**Comment by taimo42** [comment]
I think I found the PR which was changing this behavior. I guess it was #1469.
But would it then not be necessary to call `IsValidInterfaceFor` for interface types instead of just comparing the .Net types [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/68be167176daab0f8791fc6c6db6821803e83cec/src/GraphQL/GraphQLExtensions.cs#L119)?

**Comment by farodin91** [comment]
I'm hitting the same issue on 3.3.2.

**Comment by farodin91** [comment]
It seems it starts to lookup types then fails during recursive loading of types.
Loading 
1. load TestVertexType(VertexInterface)
2. has field to TestEdgeType (EdgeInterface)
3. load TestEdgeType
4. has field to AnotherVertexTye (VertexInterface) -> AnotherVertexType is not loaded and fails to check IsSubtypeOf in IsValidInterfaceFor
 ```
if (!IsSubtypeOf(found.ResolvedType, field.ResolvedType, null))
                        return throwError ? throw new ArgumentException($"Type {type.GetType().GetFriendlyName()} with name '{type.Name}' does not implement interface {iface.GetType().GetFriendlyName()} with name '{iface.Name}'. Field '{field.Name}' must be of type '{field.ResolvedType}' or covariant from it, but in fact it is of type '{found.ResolvedType}'.") : false;
```

**Comment by Shane32** [comment]
@taimo42 @farodin91 If someone would like to branch off of ‘develop’ and add a test demonstrating this bug, it would be helpful.

**Comment by taimo42** [comment]
Sorry, in the meantime I was assigned to another project and therefore will not have time to follow up this issue.
As I mentioned in my previous post, I guess that the issue would be fixed if for example `IsValidInterfaceFor` is called recursively if `IsSubtypeOf` fails. But I haven't tested this.
When I faced this issue last year, I just used the cast in the query as a workaround.

**Comment by Shane32** [comment]
I think this would be easy enough to solve with a proper demo of the issue.  Based on this I will close the issue:

> Sorry, in the meantime I was assigned to another project and therefore will not have time to follow up this issue.
