### ISSUE TITLE
Error when using an Interface on ObjectGraphType

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [graphql-dotnet/graphql-dotnet#2461]
## Description

With version 3.x, we could do `public class MyType : ObjectGraphType<IMyType>`. However, with v 4.x, this now gives an error. Looks like we always must pass in a concrete type and there is no indication as to the constraint. 

### Steps to reproduce

Pls check this repo where I have a simple set up showing the problem. 

https://github.com/EmmanuelPonnudurai/GraphqlDotnetInterfaceIssue

![image](https://user-images.githubusercontent.com/14484652/112871524-55d8eb80-908d-11eb-9a41-d4e2fbeee54e.png)

![image](https://user-images.githubusercontent.com/14484652/112871437-43f74880-908d-11eb-88e3-0a57a8bd848a.png)

### Expected result

It should work OR we need to specify a constraint on ObjectGraphType< T > specifying that T should be a class.

### Actual result

End up with an exception and unable to move to v4.x unless we make this change. But I'd like to know the reasoning of this and is this going to be this way going forward ?

### Environment

Windows 10.

**Comment by sungam3r** [comment]
Well... Maybe add `: IDroid` to `Droid` declaration?

**Comment by sungam3r** [comment]
From `ExecutionStrategy.cs`:
```csharp
if (objectType?.IsTypeOf != null && !objectType.IsTypeOf(result))
            {
                throw new InvalidOperationException($"'{result}' value of type '{result.GetType()}' is not allowed for '{objectType.Name}'. Either change IsTypeOf method of '{objectType.Name}' to accept this value or return another value from your resolver.");
            }
```

It seems logical to me.

**Comment by Shane32** [comment]
So in other words, since `Droid` does not implement `IDroid`, by default it is refused as a source object for `ObjectGraphType<IDroid>`.  Either make `Droid` implement `IDroid`, or you can override the type check by clearing the `IsTypeOf` delegate.  Making that change alone now causes an invalid cast exception with the field builders, since the expression syntax field builders precompile the field resolver.  You'd have to make this change for it to work:

```cs
    public class DroidType : ObjectGraphType<IDroid>
    {
        public DroidType()
        {
            // override type checking
            IsTypeOf = null;
            // do not use field builder expression syntax
            Field<StringGraphType>("Id", "The Id of the Droid.");
            Field<StringGraphType>("Name", "The name of the Droid.");
        }
    }
```

Again, if you can change your data classes, this is much easier and no changes are necessary to `DroidType`:

```cs
    public class Droid : IDroid
```

**Comment by Shane32** [comment]
The error message returned is the following:
```
'GraphQL.Net_InterfaceAsGraphType.Droid' value of type 'GraphQL.Net_InterfaceAsGraphType.Droid' is not allowed for 'DroidType'. Either change IsTypeOf method of 'DroidType' to accept this value or return another value from your resolver.
```
The message seems appropriate given the problem (`Droid` does not implement `IDroid`).  @sungam3r do think any changes need to be made to the error message? Including the valid type name would probably be a breaking change unfortunately, so I would probably leave it as-is.  Note that this error is a "Processing Error" and can be handled or logged via the `UnhandledExeceptionDelegate` like in the following sample:
```cs
execOptions.UnhandledExceptionDelegate = ctx =>
{
    Console.WriteLine(ctx.Exception.Message);
};
```
Processing errors are, by default, not returned back with the graphql result as it may expose sensitive information regarding the nature of your code.  This can be configured by configuring the `IErrorInfoProvider` passed to the serializer.  Often you may display all errors while in debug mode, and in release mode they are hidden and/or logged.  You can read more on this here: https://graphql-dotnet.github.io/docs/getting-started/errors

**Comment by EmmanuelPonnudurai** [comment]
Thank you for your responses @sungam3r @Shane32. I can see it working correctly with `Droid: IDroid`. This is however a stripped-down version of another issue I was seeing after migrating to v4. I'm going to take a closer look at that and if I see any issue. I shall update this thread.

Note that the original issue I saw was related to `InputObjectGraphType`. 

This can be marked as resolved now. Thank you for your help again.

**Comment by Shane32** [comment]
You’re welcome!
